In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [3]:
devices = pd.read_csv('original/devices_list.csv',sep=";")
devices[]
devices

,Device_ID,Category_ID,Category,Device,Mac_Address,eth.src,eth.dst,Wireless/Wired
0,1,1,Hubs,Smart_Things,d0:52:a8:00:67:5e,d0:52:a8:00:67:5e,d0:52:a8:00:67:5e,Wired
1,2,1,Hubs,Amazon_Echo,44:65:0d:56:cc:d3,44:65:0d:56:cc:d3,44:65:0d:56:cc:d3,Wireless
2,3,2,Cameras,Netatmo_Welcome,70:ee:50:18:34:43,70:ee:50:18:34:43,70:ee:50:18:34:43,Wireless
3,4,2,Cameras,TP-Link_Day_Night_Cloud_camera,f4:f2:6d:93:51:f1,f4:f2:6d:93:51:f1,f4:f2:6d:93:51:f1,Wireless
4,5,2,Cameras,Samsung_SmartCam,00:16:6c:ab:6b:88,00:16:6c:ab:6b:88,00:16:6c:ab:6b:88,Wireless
5,6,2,Cameras,Dropcam,30:8c:fb:2f:e4:b2,30:8c:fb:2f:e4:b2,30:8c:fb:2f:e4:b2,Wireless
6,7,2,Cameras,Insteon_Camera,00:62:6e:51:27:2e,00:62:6e:51:27:2e,00:62:6e:51:27:2e,Wired
7,7,2,Cameras,Insteon_Camera,e8:ab:fa:19:de:4f,e8:ab:fa:19:de:4f,e8:ab:fa:19:de:4f,Wireless
8,8,2,Cameras,Withings_Smart_Baby_Monitor,00:24:e4:11:18:a8,00:24:e4:11:18:a8,00:24:e4:11:18:a8,Wired
9,9,3,Switches_Triggers,Belkin_Wemo_switch,ec:1a:59:79:f4:89,ec:1a:59:79:f4:89,ec:1a:59:79:f4:89,Wireless
10,10,3,Switches_Triggers,TP-Link_Smart_plug,50:c7:bf:00:56:39,50:c7:bf:00:56:39,50:c7:bf:00:56:39,Wireless
11,11,3,Switches_Triggers,iHome,74:c6:3b:29:d7:1d,74:c6:3b:29:d7:1d,74:c6:3b:29:d7:1d,Wireless
12,12,3,Switches_Triggers,Belkin_wemo_motion_sensor,ec:1a:59:83:28:11,ec:1a:59:83:28:11,ec:1a:59:83:28:11,Wireless
13,13,4,Air_quality_sensor,NEST_Protect_smoke_alarm,18:b4:30:25:be:e4,18:b4:30:25:be:e4,18:b4:30:25:be:e4,Wireless
14,14,4,Air_quality_sensor,Netatmo_weather_station,70:ee:50:03:b8:ac,70:ee:50:03:b8:ac,70:ee:50:03:b8:ac,Wireless
15,15,5,Healcare_devices,Withings_Smart_scale,00:24:e4:1b:6f:96,00:24:e4:1b:6f:96,00:24:e4:1b:6f:96,Wireless
16,16,5,Healcare_devices,Blipcare_Blood_Pressure_meter,74:6a:89:00:2e:25,74:6a:89:00:2e:25,74:6a:89:00:2e:25,Wireless
17,17,5,Healcare_devices,Withings_Aura_smart_sleep_sensor,00:24:e4:20:28:c6,00:24:e4:20:28:c6,00:24:e4:20:28:c6,Wireless
18,18,6,Light,Light_Bulbs_LiFX Smart_Bulb,d0:73:d5:01:83:08,d0:73:d5:01:83:08,d0:73:d5:01:83:08,Wireless
19,19,7,Electronics,Triby_Speaker,18:b7:9e:02:20:44,18:b7:9e:02:20:44,18:b7:9e:02:20:44,Wireless
20,20,7,Electronics,PIX-STAR_Photo-frame,e0:76:d0:33:bb:85,e0:76:d0:33:bb:85,e0:76:d0:33:bb:85,Wireless
21,21,7,Electronics,HP_Printer,70:5a:0f:e4:9b:c0,70:5a:0f:e4:9b:c0,70:5a:0f:e4:9b:c0,Wireless
22,22,8,Tablets/Phones,Samsung_Galaxy_Tab,08:21:ef:3b:fc:e3,08:21:ef:3b:fc:e3,08:21:ef:3b:fc:e3,Wireless
23,23,8,Tablets/Phones,Android_Phone,40:f3:08:ff:1e:da,40:f3:08:ff:1e:da,40:f3:08:ff:1e:da,Wireless
24,24,8,Tablets/Phones,Iphone,d0:a6:37:df:a1:e1,d0:a6:37:df:a1:e1,d0:a6:37:df:a1:e1,Wireless
25,25,9,Laptop,MacBook/Iphone,f4:5c:89:93:cc:85,f4:5c:89:93:cc:85,f4:5c:89:93:cc:85,Wireless
26,26,9,Laptop,Laptop,74:2f:68:81:69:42,74:2f:68:81:69:42,74:2f:68:81:69:42,Wireless
27,27,9,Laptop,MacBook,ac:bc:32:d4:6f:2f,ac:bc:32:d4:6f:2f,ac:bc:32:d4:6f:2f,Wireless
28,28,10,Gateway,TPLink_Route_ Bridge_LAN,14:cc:20:51:33:ea,14:cc:20:51:33:ea,14:cc:20:51:33:ea,Wireless

In [78]:
days = ['16-09-23.csv','16-09-24.csv','16-09-25.csv','16-09-26.csv','16-09-27.csv','16-09-28.csv',
        '16-09-29.csv','16-09-30.csv','16-10-01.csv','16-10-02.csv','16-10-03.csv','16-10-04.csv',
        '16-10-05.csv','16-10-06.csv','16-10-07.csv','16-10-08.csv','16-10-09.csv','16-10-10.csv',
        '16-10-11.csv','16-10-12.csv']

devices = pd.read_csv('original/devices_list.csv',sep=";")

for day in days:
    dataset = pd.read_csv('original/'+day)
    data_src = pd.merge(dataset, devices, on=['eth.src'], how='inner')
    data_src['eth.src'] = data_src['Device_ID']
    data = data_src[['Packet ID','TIME','Size','eth.src','eth.dst_x','IP.src','IP.dst','IP.proto','port.src','port.dst']]
    data.rename(columns={'eth.dst_x':'eth.dst'}, inplace=True)
    data.rename(columns={'eth.src':'device_src'}, inplace=True)
    
    data_dst = pd.merge(data, devices, on=['eth.dst'], how='inner')
    data_dst['eth.dst'] = data_src['Device_ID']
    data_dst.rename(columns={'eth.dst':'device_dest'}, inplace=True)
    data_dst[['Packet ID','TIME','Size','device_src','device_dest','IP.src','IP.dst','IP.proto','port.src','port.dst']].to_csv('dataset/crude/f-'+day)

In [ ]:
devices

In [59]:
data_complete.head()

,Packet ID,TIME,Size,Mac_Address,eth.dst,IP.src,IP.dst,IP.proto,port.src,port.dst,Device_ID,Category_ID,Category,Device,conection
0,1,1474984800,54,14:cc:20:51:33:ea,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
1,5,1474984801,66,14:cc:20:51:33:ea,30:8c:fb:2f:e4:b2,52.87.241.159,192.168.1.106,6,443,40767,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
2,14,1474984802,66,14:cc:20:51:33:ea,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
3,15,1474984802,90,14:cc:20:51:33:ea,44:65:0d:56:cc:d3,204.11.201.12,192.168.1.240,17,123,55872,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
4,20,1474984802,68,14:cc:20:51:33:ea,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless

In [60]:
data_complete.shape

(1893517, 15)

In [61]:
data_complete['Mac_Address'] = data_complete['Device_ID']

In [62]:
data_complete.head()

,Packet ID,TIME,Size,Mac_Address,eth.dst,IP.src,IP.dst,IP.proto,port.src,port.dst,Device_ID,Category_ID,Category,Device,conection
0,1,1474984800,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
1,5,1474984801,66,29,30:8c:fb:2f:e4:b2,52.87.241.159,192.168.1.106,6,443,40767,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
2,14,1474984802,66,29,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
3,15,1474984802,90,29,44:65:0d:56:cc:d3,204.11.201.12,192.168.1.240,17,123,55872,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless
4,20,1474984802,68,29,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638,29,10,Gateway,TPLink_Route_ Bridge_LAN,Wireless

In [63]:
data_complete.shape

(1893517, 15)

In [64]:
data = data_complete[['Packet ID','TIME','Size','Mac_Address','eth.dst','IP.src','IP.dst','IP.proto','port.src','port.dst']]

In [65]:
data.shape

(1893517, 10)

In [66]:
data.rename(columns={'Mac_Address':'device_src'}, inplace=True)

In [67]:
data.rename(columns={'eth.dst':'Mac_Address'}, inplace=True)

In [68]:
data.head()

,Packet ID,TIME,Size,device_src,Mac_Address,IP.src,IP.dst,IP.proto,port.src,port.dst
0,1,1474984800,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173
1,5,1474984801,66,29,30:8c:fb:2f:e4:b2,52.87.241.159,192.168.1.106,6,443,40767
2,14,1474984802,66,29,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638
3,15,1474984802,90,29,44:65:0d:56:cc:d3,204.11.201.12,192.168.1.240,17,123,55872
4,20,1474984802,68,29,18:b7:9e:02:20:44,46.105.38.79,192.168.1.120,6,5228,54638

In [69]:
data_merge = pd.merge(data, devices, on=['Mac_Address'], how='inner')

In [70]:
data_merge.head()

,Packet ID,TIME,Size,device_src,Mac_Address,IP.src,IP.dst,IP.proto,port.src,port.dst,Device_ID,Category_ID,Category,Device,conection
0,1,1474984800,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
1,60,1474984809,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
2,61,1474984809,123,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
3,98,1474984819,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
4,134,1474984829,54,29,d0:52:a8:00:67:5e,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired

In [71]:
data_merge['Mac_Address'] = data_merge['Device_ID']

In [72]:
data_merge.head()

,Packet ID,TIME,Size,device_src,Mac_Address,IP.src,IP.dst,IP.proto,port.src,port.dst,Device_ID,Category_ID,Category,Device,conection
0,1,1474984800,54,29,1,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
1,60,1474984809,54,29,1,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
2,61,1474984809,123,29,1,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
3,98,1474984819,54,29,1,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired
4,134,1474984829,54,29,1,54.210.202.2,192.168.1.196,6,443,2173,1,1,Hubs,Smart_Things,Wired

In [73]:
final_data = data_merge[['Packet ID','TIME','Size','device_src','Mac_Address','IP.src','IP.dst','IP.proto','port.src','port.dst']]

In [74]:
final_data.rename(columns={'Mac_Address':'device_dest'}, inplace=True)

In [75]:
final_data.head()

,Packet ID,TIME,Size,device_src,device_dest,IP.src,IP.dst,IP.proto,port.src,port.dst
0,1,1474984800,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
1,60,1474984809,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
2,61,1474984809,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
3,98,1474984819,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
4,134,1474984829,54,29,1,54.210.202.2,192.168.1.196,6,443,2173

In [76]:
final_data

,Packet ID,TIME,Size,device_src,device_dest,IP.src,IP.dst,IP.proto,port.src,port.dst
0,1,1474984800,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
1,60,1474984809,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
2,61,1474984809,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
3,98,1474984819,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
4,134,1474984829,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
5,177,1474984839,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
6,216,1474984850,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
7,263,1474984860,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
8,311,1474984868,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
9,315,1474984868,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
10,379,1474984878,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
11,416,1474984888,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
12,445,1474984893,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
13,446,1474984893,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
14,493,1474984903,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
15,601,1474984913,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
16,651,1474984923,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
17,706,1474984934,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
18,750,1474984944,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
19,808,1474984952,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
20,809,1474984952,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
21,858,1474984962,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
22,905,1474984972,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
23,963,1474984982,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
24,1042,1474984993,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
25,1108,1474985003,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
26,1137,1474985010,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
27,1138,1474985010,123,29,1,54.210.202.2,192.168.1.196,6,443,2173
28,1192,1474985021,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
29,1229,1474985031,54,29,1,54.210.202.2,192.168.1.196,6,443,2173
...,...,...,...,...,...,...,...,...,...,...
1865518,1007552,1475027550,90,8,29,192.168.1.103,132.163.4.103,17,48329,123
1865519,1008247,1475027574,102,8,29,192.168.1.103,23.234.53.67,17,59960,10001
1865520,1008248,1475027574,102,8,29,192.168.1.103,50.7.44.82,17,59960,10001
1865521,1008249,1475027574,102,8,29,192.168.1.103,50.7.114.59,17,59960,10001
1865522,1008250,1475027574,102,8,29,192.168.1.103,50.7.176.18,17,59960,10001
1865523,1008251,1475027574,102,8,29,192.168.1.103,23.234.53.61,17,59960,10001
1865524,1008252,1475027574,102,8,29,192.168.1.103,120.24.76.167,17,59960,10001
1865525,1008253,1475027574,102,8,29,192.168.1.103,115.29.178.199,17,59960,10001
1865526,1009219,1475027606,73,8,29,192.168.1.103,192.168.1.1,17,34703,53
1865527,1009226,1475027607,90,8,29,192.168.1.103,128.138.140.44,17,47924,123
1865528,1009243,1475027609,90,8,29,192.168.1.103,128.138.140.44,17,47924,123
1865529,1009265,1475027610,90,8,29,192.168.1.103,128.138.140.44,17,47924,123
1865530,1009313,1475027614,102,8,29,192.168.1.103,23.234.53.67,17,59960,10001
1865531,1009314,1475027614,102,8,29,192.168.1.103,50.7.44.82,17,59960,10001
1865532,1009315,1475027614,102,8,29,192.168.1.103,50.7.114.59,17,59960,10001
1865533,1009316,1475027614,102,8,29,192.168.1.103,50.7.176.18,17,59960,10001
1865534,1009317,1475027614,102,8,29,192.168.1.103,23.234.53.61,17,59960,10001
1865535,1009318,1475027614,102,8,29,192.168.1.103,120.24.76.167,17,59960,10001
1865536,1009319,1475027614,102,8,29,192.168.1.103,115.29.178.199,17,59960,10001
1865537,1010922,1475027653,102,8,29,192.168.1.103,23.234.53.67,17,59960,10001
1865538,1010923,1475027653,102,8,29,192.168.1.103,50.7.44.82,17,59960,10001
1865539,1010924,1475027653,102,8,29,192.168.1.103,50.7.114.59,17,59960,10001
1865540,1010925,1475027653,102,8,29,192.168.1.103,50.7.176.18,17,59960,10001
1865541,1010926,1475027653,102,8,29,192.168.1.103,23.234.53.61,17,59960,10001
1865542,1010927,1475027653,102,8,29,192.168.1.103,120.24.76.167,17,59960,10001
1865543,1010928,1475027653,102,8,29,192.168.1.103,115.29.178.199,17,59960,10001
1865544,1011741,1475027666,73,8,29,192.168.1.103,192.168.1.1,17,46407,53
1865545,1011768,1475027667,90,8,29,192.168.1.103,216.228.192.69,17,58423,123
1865546,1011794,1475027669,90,8,29,192.168.1.103,216.228.192.69,17,58423,123
1865547,1011815,1475027670,90,8,29,192.168.1.103,216.228.192.69,17,58423,123

In [77]:
final_data.to_csv('dataset/f-16-09-28.csv')